services:

  nginx:
      image: nginx:alpine
      container_name: nginx
      restart: unless-stopped
      tty: true
      ports:
        - "8200:80" # voting-admin application
      volumes:
        - .docker/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
        - .:/var/www/:delegated
      depends_on:
        - app
      networks:
        - app-network

  app:
    build: .
    ports:
      - "5173:5173" # Vite
    volumes:
      - .:/var/www:delegated
    command: ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge