services:
  app:
    build: .
    ports:
      - "8000:80"
      - "5173:5173"
    volumes:
      - .:/var/www
      - /var/www/vendor/
      - /var/www/node_modules/
    command: ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge