services:

  forward-proxy_voting-admin:
      image: nginx:alpine
      container_name: forward-proxy_voting-admin
      restart: unless-stopped
      tty: true
      ports:
        - "8200:80" # voting-admin application
      volumes:
        - .docker/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
        - .:/var/www/:delegated
      depends_on:
        - voting-admin_app
      networks:
        - voting-admin_app-network

  voting-admin_app:
    build: .
    container_name: voting-admin_app
    ports:
      - "5173:5173" # Vite
    volumes:
      - .:/var/www:delegated
    command: ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    networks:
      - voting-admin_app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  voting-admin_app-network:
    driver: bridge