services:
  app:
    build: .
    ports:
      - "5173:5173" # Vite
      - "8200:80" # voting-admin application
    volumes:
      - .:/var/www
    command: ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge